# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path
name: Maven Package

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Set up Heroku CLI
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh
      env:
         HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Connect to Heroku
      run: |
          heroku login -i
      env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Run PostgreSQL Command
      run: |
          heroku pg:psql postgresql-flat-54928 --app HEROKU_APP_NAME
          # Example: heroku pg:info -a your-heroku-app-name
      env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_URL: ${{ secrets.DB_URL }}

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
